### ISSUE TITLE
WKWebView的问题

### ISSUE THREAD

**Issue by niuxinhuai** [GIKICoder/GMenuController#2]
大佬请问下，这个可以用到WKWebView吗？WK局限性好多

**Comment by niuxinhuai** [comment]
我试了一下，用在WKWebView中不行的。大佬有思路解决吗

**Comment by GIKICoder** [comment]
不响应系统的menuview.如果能得到在webView中选中的范围.应该是可以的. 你可以参考一下GRichLabel.里面就是使用的GMenuController  https://github.com/GIKICoder/GRichLabel

**Comment by niuxinhuai** [comment]
我今天试了一下，取消掉系统的menu弹框，使用自定义。但是结果并不理想。webView是可以的，但是WKWebView就不行了

**Comment by GIKICoder** [comment]
试了一下. wkwebView 是可以弹出GMenuController. 但是做不到系统的弹出跟随效果.拿不到选中区域.
