### ISSUE TITLE
点击任何区域，则隐藏按钮

### ISSUE THREAD

**Issue by pengpeng-wang** [GIKICoder/GMenuController#4]
点击任何区域，则隐藏按钮，这个需求怎么做。系统的是，点击任何区域，就消失了

**Comment by GIKICoder** [comment]
这个你可以在页面自己去加点击事件.然后在showMenu的情况下.接收到点击事件然后hide... 或者等一下我增加个api.可以先star.等个更新.

**Comment by pengpeng-wang** [comment]
我觉得是在 GMenuEffectsWindow 的hitTest方法里去隐藏。如果在我的消息页面，实现hitTest，点击导航栏不会走hitTest。所以在你的window里的hitTest去隐藏最好了，这样就应该和系统的是一样的了。

**Comment by GIKICoder** [comment]
可以了. update 一下代码... 如果不需要自动隐藏    设置[GMenuController sharedMenuController].menuViewContainer.hasAutoHide = NO;

**Comment by pengpeng-wang** [comment]
可以了，谢谢！🙏
