### ISSUE TITLE
Frame的位置不对

### ISSUE THREAD

**Issue by xieguangming** [GIKICoder/GMenuController#5]
使用你的GMenuItem， 在聊天界面的tableviewcell 上面复制,粘贴， 发现位置不对， 使用系统的UIMenuItem没有问题，  不知道是什么原因。。

 [[GMenuController sharedMenuController] setTargetRect:sender.frame inView:self.view]; 这个方法，我传的frame值是没有问题的， 但是在显示的时候位置不对。

**Comment by xieguangming** [comment]
可以帮忙看一下吗？

**Comment by GIKICoder** [comment]
可以截图发上来看一下吗.

**Comment by xieguangming** [comment]
搞定了， inView参数传的不对，应该传sender控件的superview.  这个问题已经解决。 谢谢楼主！
