### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by wangxumin** [GIKICoder/GMenuController#6]
你这有很大的性能问题,我是在点击cell的时候初始换显示,滑动tableView的时候隐藏menu,界面就非常卡顿,CPU消耗在90%以上

**Comment by GIKICoder** [comment]
你可以贴一下代码么.我测试了一下. 没看到内存暴涨的情况. menuview 会实时释放的... menuContainer.全局持有一个实例. 不过也不会占用太多内存.

**Comment by wangxumin** [comment]
@GIKICoder 加了个判断好了 if ([GMenuController sharedMenuController].isMenuVisible) {
        [[GMenuController sharedMenuController] setMenuVisible:NO];
    }  ,之前没加判断就是有问题
