### ISSUE TITLE
menuItem 分格线存在缺陷

### ISSUE THREAD

**Issue by sujiewen** [GIKICoder/GMenuController#8]
menuItem 分格线存在缺陷,会绘制到三角形里面呢

![simulator screen shot - iphone 6s - 2018-10-15 at 16 02 59](https://user-images.githubusercontent.com/1973318/46937444-e7a63700-d093-11e8-98f9-1a6bcea62a68.png)

**Comment by GIKICoder** [comment]
这个是故意实现的一个效果。 可以看一下系统的 分割线就是贯穿的。

**Comment by sujiewen** [comment]
系统不是贯穿的
