### ISSUE TITLE
statusbar 存在问题？

### ISSUE THREAD

**Issue by sujiewen** [GIKICoder/GMenuController#9]
调用前效果：
![simulator screen shot - iphone xs max - 2018-10-25 at 11 52 29](https://user-images.githubusercontent.com/1973318/47476578-ad872300-d853-11e8-9c23-9f1d0967d722.png)
调用后效果：
![simulator screen shot - iphone 6s - 2018-10-25 at 12 43 40](https://user-images.githubusercontent.com/1973318/47476585-c099f300-d853-11e8-9b92-4b21e0b55468.png)

**Comment by GIKICoder** [comment]
你用哪种方式设置的statusBarStyle？

**Comment by sujiewen** [comment]
UIStatusBarStyleLightContent
View controller-based status bar appearance = YES

**Comment by GIKICoder** [comment]
我跑了一下demo ，没有复现这个问题。

**Comment by sujiewen** [comment]
初始是状态栏字体，弹出菜单后，就变黑色了哦

[GMenuController-master.zip](https://github.com/GIKICoder/GMenuController/files/2517396/GMenuController-master.zip)

**Comment by sujiewen** [comment]
@GIKICoder 有解决方法吗？

**Comment by norman452003** [comment]
同样遇到这问题  只好不用window了 加到一个全屏的view上  view再添加到自己的window上

**Comment by GIKICoder** [comment]
看了下，应该是window没有添加rootvc的原因。加个rootvc应该就没问题了  
  static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
            inst = [self new];
            inst.frame = (CGRect){.size = GMenuScreenSize()};
            inst.userInteractionEnabled = NO;
            inst.windowLevel =  UIWindowLevelStatusBar + 1;
            inst.hidden = NO;
            UIViewController * vc = [[UIViewController alloc] init];
            inst.rootViewController = vc;
            vc.view.frame = CGRectZero;
            // for iOS 9:
            inst.opaque = NO;
            inst.backgroundColor = [UIColor clearColor];
            inst.layer.backgroundColor = [UIColor clearColor].CGColor;
    });

**Comment by GIKICoder** [comment]
[bugFix](https://github.com/GIKICoder/GMenuController/commit/00a0013fcd96c4246649fecbbdc74e5b3a22fefd)

**Comment by XavierLost** [comment]
ios 12 还是会出现上面的问题 白色的状态栏变成黑色的了

**Comment by JonathanChen123** [comment]
自定义一个UIViewController，statusBar为白色，可以解决该问题。
 FYBaseViewController * vc = [[FYBaseViewController alloc] init];
--->替换
UIViewController * vc = [[UIViewController alloc] init];

> ios 12 还是会出现上面的问题 白色的状态栏变成黑色的了

自定义一个UIViewController，statusBar为白色，可以解决该问题。
 FYBaseViewController * vc = [[FYBaseViewController alloc] init];
--->替换
UIViewController * vc = [[UIViewController alloc] init];
